#controllers:
#    resource: ../src/Controller/
#    type: annotation
#
#kernel:
#    resource: ../src/Kernel.php
#    type: annotation


main:
    path:/main
    controller:App\Controller\MainController::index