controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


welcome:
    path: /welcome
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\MainController::index

custom:
    path: /custom
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\MainController::show